name: CI

on:
  push:
  pull_request:
      branches: [master]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cc: [clang, gcc]
        kernel: [ish, linux]
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: true
      - uses: actions/setup-python@v2
        with:
            python-version: '3.x'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libarchive-dev
          pip3 install meson ninja
      - name: Clone Linux
        if: matrix.kernel == 'linux'
        run: deps/clone-linux.sh
      - name: Build
        run: |
          meson build -Dengine=jit -Dkernel=${{matrix.kernel}}
          ninja -C build
        env:
          CC: ${{matrix.cc}}
      - name: Test
        if: matrix.kernel == 'ish'
        run: ninja -C build test

  build-mac:
    runs-on: macos-11
    strategy:
      matrix:
        kernel: [ish, linux]
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: true
      - name: Install dependencies
        run: |
          brew install llvm ninja libarchive
          pip3 install meson
      - name: Clone Linux
        if: matrix.kernel == 'linux'
        run: deps/clone-linux.sh
      - name: Build
        if: matrix.kernel == 'ish'
        run: xcodebuild -project iSH.xcodeproj -scheme iSH -arch arm64 -sdk iphoneos CODE_SIGNING_ALLOWED=NO
      - name: Build
        if: matrix.kernel == 'linux'
        run: xcodebuild -project iSH.xcodeproj -scheme iSH+Linux -arch x86_64 -sdk iphonesimulator CODE_SIGNING_ALLOWED=NO
