
	




					
name: Build and Test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Build Tools
        run: |
          brew install meson ninja

      - name: Setup Meson Build
        run: |
          meson setup build

      - name: Compile (Meson)
        run: |
          meson compile -C build


