name: Deploy Site
on:
  release:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Deploy
      run: curl -d {} $NETLIFY_DEPLOY_HOOK
      env:
        NETLIFY_DEPLOY_HOOK: ${{ secrets.NETLIFY_DEPLOY_HOOK }}
